WEBUI/Models/FigureStore/CirlcesViewForAddingToStore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WEBUI.Models.Figures;

namespace WEBUI.Models.FigureStore
{
    public class CirlcesViewForAddingToStore
    {
        public IEnumerable<CirlceView> Cirlces { get; set; }//todo
        public PagingInfoView PagingInfo { get; set; }
        public int StoreId { get; set; }
        public string StoreName { get; set; }

    }

}

WEBUI/Models/FigureStore/FigureStoreCreatingAndEditingView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WEBUI.Models.FigureStore
{
    public class FigureStoreCreatingAndEditingView
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Figure store name")]
        [StringLength(10, ErrorMessage = "The {0} must be between {1} and {2} characters long.", MinimumLength = 2)]
        public string Name { get; set; }
    }
}

WEBUI/Models/FigureStore/FigureStoreDetailView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WEBUI.Models.Figures;

namespace WEBUI.Models.FigureStore
{
    public class FigureStoreDetailView
    {
         public int Id { get; private set; }
        public string Name { get; private set; }
        public int CountOfFigures { get; private set; }
        public float Area { get; private set; }
        public List<FigureView> Figures { get; set; }//todo
        public FigureStoreDetailView(int id, string name, int numberOfFigures, float area)
        {
            Id = id;
            Name = name;
            CountOfFigures = numberOfFigures;
            Area = area;
        }
        public PagingInfoView PagingInfo { get; set; }

    }
}

WEBUI/Models/FigureStore/FigureStoreView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WEBUI.Models.FigureStore
{
    public class FigureStoreView
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
        public int CountOfFigures { get; private set; }
        public float Area { get; private set; }

        public FigureStoreView(int id, string name, int numberOfFigures, float area)
        {
            Id = id;
            Name = name;
            CountOfFigures = numberOfFigures;
            Area = area;
        }

    }
}

WEBUI/Models/FigureStore/FigureStoresView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WEBUI.Models.FigureStore
{
    public class FigureStoresView
    {
        public IEnumerable<FigureStoreView> FigureStores { get; set; }//todo
        public PagingInfoView PagingInfo { get; set; }
    }
}

WEBUI/Models/FigureStore/RectanglesViewForAddingToStore.cs
using System.Collections.Generic;
using WEBUI.Models.Figures;

namespace WEBUI.Models.FigureStore
{
    public class RectanglesViewForAddingToStore
    {
        public IEnumerable<RectangleView> Rectangles { get; set; }//todo
        public PagingInfoView PagingInfo { get; set; }
        public int StoreId { get; set; }
        public string StoreName { get; set; }
    }
}

WEBUI/Models/FigureStore/SquaresViewForAddingToStore.cs
using System.Collections.Generic;
using WEBUI.Models.Figures;

namespace WEBUI.Models.FigureStore
{
    public class SquaresViewForAddingToStore
    {
        public IEnumerable<SquareView> Squares { get; set; }//todo
        public PagingInfoView PagingInfo { get; set; }
        public int StoreId { get; set; }
        public string StoreName { get; set; }

    }
}

WEBUI/Controllers/FigureStoreController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using BusinessLayer;
using BusinessLayer.Entities;
using BusinessLayer.Exceptions;
using WEBUI.Models;
using WEBUI.Models.Figures;
using WEBUI.Models.Figures.Circle;
using WEBUI.Models.FigureStore;

namespace WEBUI.Controllers
{
    public class FigureStoreController : Controller
    {
        string GetConnectionStringToBD()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["ConnectionToBD"].ConnectionString;
            return connectionString;
        }
        string GetConnectionStringToFile()
        {
            // by default seek bd File near .exe; so in bin\Debug\
            // so need to copy in that place. 
            // if create Release also need to copy bin\Release\
            // and by the wat this directory are Temp one))
            // so copy to the folder at more high level
            // кроме того что єто такое, зачем єто нужно - "занимательная вивисекция

            // https://politikus.ru/articles/politics/56971-malysh-i-karlson-nauchnyy-perevod.html
            string connectionString = ConfigurationManager.ConnectionStrings["ConnectionToFile"].ConnectionString;
            AdjustDataDirectory();
            return connectionString;
        }

        private void AdjustDataDirectory()
        {
            var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            string relative = @"..\";
            string absolute = Path.GetFullPath(Path.Combine(baseDirectory, relative));// todo
            Console.WriteLine("path= {0}", absolute);
            AppDomain.CurrentDomain.SetData("DataDirectory", absolute);
        }
        //
        // GET: /Figure/
        private FiguresService _figuresService;
        public FigureStoreController()
        {
            _figuresService = new FiguresService(GetConnectionStringToFile());
        }
        public ActionResult FigureStoreList()//+
        {
            try
            {
                List<FigureStoreView> fsv = new List<FigureStoreView>();
                foreach (FiguresStoreBll fs in _figuresService.GetAllStores())
                {
                    fsv.Add(new FigureStoreView(fs.Id, fs.Name, fs.Count, fs.GetAreas()));
                }
                FigureStoresView fsvList = new FigureStoresView() { FigureStores = fsv };
                return View(fsvList);
            }
            catch (Exception ex)
            {
                return HttpNotFound(ex.Message);
            }
        }
        public ActionResult FigureStoreEdit(int? id)//+
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            try
            {
                FiguresStoreBll fs = _figuresService.GetStoreById(id.Value);
                List<FigureView> figures = new List<FigureView>();
                foreach (var item in fs.Figures)
                {
                    figures.Add(FigureViewFactory.Create(item));
                }

                FigureStoreDetailView fsdv = new FigureStoreDetailView(fs.Id, fs.Name, fs.Count, fs.GetAreas());
                fsdv.Figures = figures;
                return View(fsdv);
            }
            catch (DataNotFoundException ex)
            {
                return RedirectToAction("DataNotFound", "Error", new { message = ex.Message });
            }
            catch (Exception ex)
            {
                return HttpNotFound(ex.Message);
            }
        }

        public ActionResult StoreCreate()// +
        {
            return View();
        }

        [HttpPost]
        public ActionResult StoreCreate(FigureStoreCreatingAndEditingView fs)// +
        {
            if (ModelState.IsValid)//todo else
            {
                try
                {
                    _figuresService.CreateFigureStore(new FiguresStoreBll(0, fs.Name));
                    return RedirectToAction("FigureStoreList");
                }
                catch (Exception ex)
                {
                    return HttpNotFound(ex.Message);
                }
            }
            return View(fs);
        }
        public ActionResult StoreEdit(int? id)// +
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            try
            {
                FiguresStoreBll fs = _figuresService.GetStoreById(id.Value);
                FigureStoreCreatingAndEditingView fscv = new FigureStoreCreatingAndEditingView() { Id = fs.Id, Name = fs.Name };
                return View(fscv);
            }
            catch (DataNotFoundException ex)
            {
                return RedirectToAction("DataNotFound", "Error", new { message = ex.Message });
            }
            catch (Exception ex)
            {
                return HttpNotFound(ex.Message);
            }
        }
        [HttpPost]
        public ActionResult StoreEdit(FigureStoreCreatingAndEditingView fs)// +
        {
            if (ModelState.IsValid)
            {
                //Range validation where value is with comma and not with dot
                //https://laracasts.com/discuss/channels/general-discussion/validate-numeric-with-both-comma-and-dot-nottation?page=1
                {
                    try
                    {
                        _figuresService.UpdateStore(new FiguresStoreBll(fs.Id, fs.Name));
                        return RedirectToAction("FigureStoreList");
                    }
                    catch (DataNotFoundException ex)
                    {
                        return RedirectToAction("DataNotFound", "Error", new { message = ex.Message });
                    }
                    catch (Exception ex)
                    {
                        return HttpNotFound(ex.Message);
                    }
                }

            }
            return View(fs);
        }

        [HttpPost]
        public ActionResult FigureStoreDelete(int? id)//+
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            try
            {
                var fs = _figuresService.GetStoreById(id.Value);
                if (fs.Count > 0)
                    return RedirectToAction("DataCouldNotBeDeleted", "Error", new { message = "Cannot remove storage. The storage " + fs.Name + " is not empty" });
                _figuresService.DeleteStore(id.Value);
                return RedirectToAction("FigureStoreList");
            }
            catch (DataNotFoundException ex)
            {
                return RedirectToAction("DataNotFound", "Error", new { message = ex.Message });
            }
            catch (Exception ex)
            {
                return HttpNotFound(ex.Message);
            }
        }
        public ActionResult CirclesForAdd(int? storeId)//+ 
        {
            if (storeId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            try
            {
                FiguresStoreBll fs = _figuresService.GetStoreById(storeId.Value);
                List<CirlceView> cirlces = new List<CirlceView>();
                foreach (var item in _figuresService.GetAllCirlces())
                {
                    cirlces.Add(new CirlceView() { Id = item.Id, Name = item.Name, Radius = item.Radius, Area = item.GetArea() });
                }

                CirlcesViewForAddingToStore c = new CirlcesViewForAddingToStore()
                {
                    Cirlces = cirlces,
                    StoreId = fs.Id,
                    StoreName = fs.Name,
                    PagingInfo = new PagingInfoView
                    {
                        CurrentPage = 1,
                        ItemsPerPage = 10,
                        TotalItems = 1
                    },
                };
                return View(c);
            }
            catch (DataNotFoundException ex)
            {
                return RedirectToAction("DataNotFound", "Error", new { message = ex.Message });
            }
            catch (Exception ex)
            {
                return HttpNotFound(ex.Message);
            }
        }
        public ActionResult AddCircle(int? storeId, int? figureId)//+
        {
            if (figureId == null || storeId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            try
            {
                _figuresService.AddCirclceInStore(storeId.Value, figureId.Value);
                return RedirectToAction("FigureStoreEdit", new { id = storeId });
            }
            catch (DataNotFoundException ex)
            {
                return RedirectToAction("DataNotFound", "Error", new { message = ex.Message });
            }
            catch (Exception ex)
            {
                return HttpNotFound(ex.Message);
            }
        }
        public ActionResult SquaresForAdd(int? storeId)//+
        {
            if (storeId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            try
            {
                List<SquareView> squares = new List<SquareView>();
                foreach (var item in _figuresService.GetAllSquares())
                {
                    squares.Add(new SquareView() { Id = item.Id, Name = item.Name, Side = item.Side, Area = item.GetArea() });
                }
                FiguresStoreBll fs = _figuresService.GetStoreById(storeId.Value);
                SquaresViewForAddingToStore c = new SquaresViewForAddingToStore()
                {
                    Squares = squares,
                    StoreId = fs.Id,
                    StoreName = fs.Name,
                    PagingInfo = new PagingInfoView
                    {
                        CurrentPage = 1,

WEBUI/Views/FigureStore/CirclesForAdd.cshtml
@model WEBUI.Models.FigureStore.CirlcesViewForAddingToStore

@{
    ViewBag.Title = "AddCircles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Choose circle to add in @Html.DisplayFor(model => model.StoreName)</h2>

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Area
        </th>
        <th>
            Radius
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Cirlces) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Area)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Radius)
        </td>
        <td>
            @Html.ActionLink("Add", "AddCircle", new { storeId = Model.StoreId, figureId = item.Id }) 

        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to Store ", "FigureStoreEdit", new { id = Model.StoreId })
</div>

WEBUI/Views/FigureStore/FigureStoreEdit.cshtml
@model WEBUI.Models.FigureStore.FigureStoreDetailView

@{
    ViewBag.Title = "FigureStoreEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="navbar-header">
        @Html.ActionLink("Figure", "AllFigures", "Figure", null, new { @class = "navbar-brand" })
        @Html.ActionLink("Figure stores", "FigureStoreList", "Figurestore", null, new { @class = "navbar-brand" })
    </div>
</div>

<div id="headerFigures">
    <div class="title">Figures Store</div>
</div>

<table class="table">
    <tr>
        <th>
            <span style="font-weight:normal">  Name:</span> @Html.DisplayFor(model => model.Name)
        </th>
        <th>
            <span style="font-weight:normal"> Area: </span> @Html.DisplayFor(model => model.Area)
        </th>
        <th>
           <span style="font-weight:normal">  Count Of Figures: </span> @Html.DisplayFor(model => model.CountOfFigures)
        </th>
        <th></th>
    </tr>
</table>

<p>
    <div class="span5">
        @Html.ActionLink("Add Circle", "CirclesForAdd", new { storeId = Model.Id })
    </div>
    <div class="span5">
        @Html.ActionLink("Add Square", "SquaresForAdd", new { storeId = Model.Id })
    </div>
    <div class="span5">
        @Html.ActionLink("Add Rectangle", "RectanglesForAdd", new { storeId = Model.Id })
    </div>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Area 
        </th>
        <th>
            Info
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Figures)
    {
        int storeId = Model.Id;
        int figureId = item.Id;
        int idInStore = item.IdInStore.Value;
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Info)
            </td>
            <td>
                @using (Html.BeginForm("RemoveFigureFrom", "FigureStore", FormMethod.Get, new { onclick = "return confirm('Are sure wants to remove ?');" }))
                {
                    @Html.HiddenFor(model => storeId)
                    @Html.HiddenFor(model => figureId)
                    @Html.HiddenFor(model => idInStore)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to Store List", "FigureStoreList")
</div>

WEBUI/Views/FigureStore/FigureStoreList.cshtml
@model WEBUI.Models.FigureStore.FigureStoresView

@{
    ViewBag.Title = "FiguresStoreList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="navbar-header">
        @Html.ActionLink("Figure", "AllFigures", "Figure", null, new { @class = "navbar-brand" })
        @Html.ActionLink("Figure stores", "FigureStoreList", "Figurestore", null, new { @class = "navbar-brand" })
    </div>
</div>

<div id="headerFigures">
    <div class="title">Figures Stores</div>
</div>

<h5>
    @Html.ActionLink("Create New", "StoreCreate")
</h5>
<table class="table">
    <tr>
        <th>
           Name
        </th>
        <th>
            Count
        </th>
        <th>
            Area
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.FigureStores) {
    int id = item.Id;
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CountOfFigures)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Area)
        </td>
        <td>
            <div class="span5">
                @using (Html.BeginForm("FigureStoreEdit", "FigureStore", FormMethod.Get))//, new { onclick = "return confirm('Are sure wants to edit ?');" }))
                {
                    @Html.HiddenFor(model => id)
                <input type="submit" value="Details" />
                }
            </div>
            <div class="span5">
                @using (Html.BeginForm("StoreEdit", "FigureStore", FormMethod.Get))//, new { onclick = "return confirm('Are sure wants to edit ?');" }))
                {
                    @Html.HiddenFor(model => id)
                     <input type="submit" value="Edit" />
                }
            </div>
            <div class="span5">
                @using (Html.BeginForm("FigureStoreDelete", "FigureStore", FormMethod.Post, new { onclick = "return confirm('Are sure wants to delete store ?');" }))
                {
                    @Html.HiddenFor(model => id)
                    <input type="submit" value="Delete" />
                }
            </div>
        </td>
    </tr>
}

</table>

WEBUI/Views/FigureStore/RectanglesForAdd.cshtml
@model WEBUI.Models.FigureStore.RectanglesViewForAddingToStore

@{
    ViewBag.Title = "RectanglesForAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Choose rectangle to add in @Html.DisplayFor(model => model.StoreName)</h2>


<table class="table">
    
    <tr>
        <th>
            Name
        </th>
        <th>
            Area
        </th>
        <th>
            Width
        </th>
        <th>
            Height
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Rectangles) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.ActionLink("Add", "AddRectangle", new { storeId = Model.StoreId, figureId = item.Id }) 
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to Store ", "FigureStoreEdit", new { id = Model.StoreId })
</div>

WEBUI/Views/FigureStore/SquaresForAdd.cshtml
@model WEBUI.Models.FigureStore.SquaresViewForAddingToStore

@{
    ViewBag.Title = "SquaresForAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Choose Square to add in @Html.DisplayFor(model => model.StoreName)</h2>


<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Area
        </th>
        <th>
            Side
        </th>
    </tr>

    @foreach (var item in Model.Squares)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Side)
            </td>
            <td>
                @Html.ActionLink("Add", "AddSquare", new { storeId = Model.StoreId, figureId = item.Id })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to Store ", "FigureStoreEdit", new { id = Model.StoreId })
</div>

WEBUI/Views/FigureStore/StoreCreate.cshtml
@model WEBUI.Models.FigureStore.FigureStoreCreatingAndEditingView

@{
    ViewBag.Title = "CreateStore";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create store</h2>
<div >
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

    <div>
        @Html.ActionLink("Back to List", "FigureStoreList")
    </div>
    <!-- todo -->
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WEBUI/Views/FigureStore/StoreEdit.cshtml
@model WEBUI.Models.FigureStore.FigureStoreCreatingAndEditingView

@{
    ViewBag.Title = "StoreEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit store </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "FigureStoreList")
</div>
<!-- todo -->
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>